<a href="https://colab.research.google.com/github/poonamkhot123/Linear-Regression/blob/main/Scikit_learn_Labelencoder_and_Ordinarencoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/content/CAR DETAILS FROM CAR DEKHO.csv")

In [3]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

# **Using Python**

In [4]:
# df.drop("name",axis=1,inplace=True)

In [5]:
# df

,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...
4335,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [6]:
# df['transmission'].value_counts()

transmission
Manual       3892
Automatic     448
Name: count, dtype: int64

In [15]:
# df['transmission']=df['transmission'].map({'Manual':0,'Automatic':1})

In [10]:
# df.sample(5)

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,tans_new
781,2017,450000,50000,Petrol,Individual,Automatic,First Owner,1
3492,2019,475000,105000,Diesel,Dealer,Automatic,First Owner,1
462,2012,350000,77000,Diesel,Individual,Manual,First Owner,0
2165,2014,390000,90000,Diesel,Individual,Manual,First Owner,0
2870,2006,85000,60000,Petrol,Individual,Manual,Second Owner,0

In [11]:
df['seller_type'].value_counts()

seller_type
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: count, dtype: int64

In [16]:
# df['seller_type'] = df['seller_type'].map({'Individual':0,'Dealer':1,'Trustmark Dealer':2})

In [14]:
# df.sample(5)

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,tans_new,seller_new
1237,2008,170000,81324,Petrol,Dealer,Manual,First Owner,0,1
1559,2012,550000,120000,Diesel,Individual,Manual,Second Owner,0,0
1031,2017,2600000,47162,Diesel,Trustmark Dealer,Automatic,First Owner,1,2
4266,2016,630000,55000,Diesel,Dealer,Manual,First Owner,0,1
762,2017,290000,20000,Petrol,Individual,Manual,First Owner,0,0

# **Using Scikitlearn**

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test=train_test_split(df.drop('fuel',axis=1),df['fuel'],test_size=0.2,random_state=42)

In [20]:
X_train

,year,selling_price,km_driven,seller_type,transmission,owner,tans_new,seller_new
227,2017,1500000,20000,0,0,First Owner,0,0
964,2018,500000,50000,0,0,First Owner,0,0
2045,2013,92800,25000,0,0,Second Owner,0,0
1025,2011,95000,70000,0,0,First Owner,0,0
4242,2017,685000,72000,1,0,First Owner,0,1
...,...,...,...,...,...,...,...,...
3444,2006,500000,50000,0,0,First Owner,0,0
466,2011,133000,80000,0,0,First Owner,0,0
3092,2016,665000,51000,1,0,First Owner,0,1
3772,2013,250999,80000,0,0,First Owner,0,0
860,2013,175000,80000,0,0,First Owner,0,0

In [21]:
X_test

,year,selling_price,km_driven,seller_type,transmission,owner,tans_new,seller_new
3978,2010,165000,80000,0,0,First Owner,0,0
1448,2019,250000,27000,0,0,First Owner,0,0
2664,2008,120000,41723,0,0,Second Owner,0,0
17,2014,450000,141000,0,0,Second Owner,0,0
1634,2016,730000,60000,0,1,Second Owner,1,0
...,...,...,...,...,...,...,...,...
3468,2007,130000,60000,0,0,Third Owner,0,0
3164,2015,350000,120000,0,0,First Owner,0,0
416,2011,150000,40000,0,0,Second Owner,0,0
1616,2017,650000,6480,2,0,First Owner,0,2
2480,2019,575000,30000,1,0,First Owner,0,1

In [22]:
y_train

227     Diesel
964     Diesel
2045    Petrol
1025    Diesel
4242    Diesel
         ...
3444    Diesel
466     Diesel
3092    Diesel
3772    Diesel
860     Petrol
Name: fuel, Length: 3472, dtype: object

In [23]:
y_test

3978    Diesel
1448    Petrol
2664    Petrol
17      Diesel
1634    Diesel
         ...
3468    Petrol
3164    Diesel
416     Diesel
1616    Petrol
2480    Petrol
Name: fuel, Length: 868, dtype: object

# **Using Scikitlearn**

In [25]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

# **1.Applying Label Encoder**

In [26]:
le = LabelEncoder()

In [28]:
y_train_scaled = le.fit_transform(y_train)
y_test_scaled = le.transform(y_test)

In [29]:
df['fuel'].value_counts()

fuel
Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: count, dtype: int64

In [31]:
y_train_scaled

array([1, 1, 4, ..., 1, 1, 4])

In [32]:
X_train

,year,selling_price,km_driven,seller_type,transmission,owner,tans_new,seller_new
227,2017,1500000,20000,0,0,First Owner,0,0
964,2018,500000,50000,0,0,First Owner,0,0
2045,2013,92800,25000,0,0,Second Owner,0,0
1025,2011,95000,70000,0,0,First Owner,0,0
4242,2017,685000,72000,1,0,First Owner,0,1
...,...,...,...,...,...,...,...,...
3444,2006,500000,50000,0,0,First Owner,0,0
466,2011,133000,80000,0,0,First Owner,0,0
3092,2016,665000,51000,1,0,First Owner,0,1
3772,2013,250999,80000,0,0,First Owner,0,0
860,2013,175000,80000,0,0,First Owner,0,0

In [41]:
oe = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_train_scaled = oe.fit_transform(X_train)
X_test_scaled = oe.transform(X_test)

In [42]:
X_train_scaled

array([[ 23., 350., 114., ...,   0.,   0.,   0.],
       [ 24., 187., 294., ...,   0.,   0.,   0.],
       [ 19.,  33., 141., ...,   2.,   0.,   0.],
       ...,
       [ 22., 229., 298., ...,   0.,   0.,   1.],
       [ 19., 101., 453., ...,   0.,   0.,   0.],
       [ 19.,  69., 453., ...,   0.,   0.,   0.]])